import type { Category, Product } from "./types";

const u = (id: string, w = 1600) =>
  `https://images.unsplash.com/photo-${id}?w=${w}&q=80&auto=format&fit=crop`;

export const seedCategories: Category[] = [
  {
    id: "c1",
    slug: "kitchen",
    name: "Kitchen",
    description: "Artisanal ceramics and premium linen textiles for your cooking space.",
    image: "/images/categories/kitchen.png",
    sort_order: 1,
  },
  {
    id: "c2",
    slug: "bedroom",
    name: "Bedroom",
    description: "Premium washed linen sheets, duvet covers and pillowcases woven to last.",
    image: "/images/categories/bedroom.png",
    sort_order: 2,
  },
  {
    id: "c3",
    slug: "lounge",
    name: "Lounge",
    description: "Cozy waffle throws and handloom blankets for comfortable spaces.",
    image: "/images/categories/lounge.png",
    sort_order: 3,
  },
  {
    id: "c4",
    slug: "bathroom",
    name: "Bathroom",
    description: "Soft, organic cotton bath sheets, waffle towels and linen wraps.",
    image: "/images/categories/bathroom.png",
    sort_order: 4,
  },
  {
    id: "c5",
    slug: "garden",
    name: "Garden",
    description: "Handloom cotton cushions and durable layers for outdoor seating.",
    image: "/images/categories/garden.png",
    sort_order: 5,
  },
  {
    id: "c6",
    slug: "garage",
    name: "Garage",
    description: "Heavy-duty linen storage baskets and organized utility essentials.",
    image: "/images/categories/garage.png",
    sort_order: 6,
  },
];

export const seedProducts: Product[] = [
  {
    id: "p1",
    slug: "cloud-percale-sheet-set",
    name: "Cloud Percale Sheet Set",
    category_slug: "bedroom",
    short_description: "Crisp, cool 400-thread percale in cloud white.",
    description:
      "Woven from long-staple cotton in a tight percale weave, the Cloud set sleeps crisp and cool all year round. Each set includes one flat sheet, one fitted sheet and two pillowcases, finished with a double-stitched hem.",
    material: "100% long-staple cotton, 400 thread count percale",
    details: [
      "Includes flat sheet, fitted sheet and two pillowcases",
      "Deep 40 cm fitted-sheet pocket",
      "Gets softer with every wash",
      "OEKO-TEX certified, free of harsh chemicals",
    ],
    care: ["Machine wash cold on gentle", "Tumble dry low", "Warm iron if desired"],
    colors: ["Cloud White", "Oat", "Sage"],
    images: [u("1631049307264-da0ec9d70304"), u("1631049035182-249067d7618e")],
    sizes: [
      { name: "Single", dimensions: "150 × 220 cm", price: 12500, compare_at_price: null },
      { name: "Double", dimensions: "200 × 220 cm", price: 14500, compare_at_price: null },
      { name: "Queen", dimensions: "230 × 250 cm", price: 16500, compare_at_price: null },
      { name: "King", dimensions: "260 × 270 cm", price: 18500, compare_at_price: null },
    ],
    badge: "Bestseller",
    featured: true,
    in_stock: true,
  },
  {
    id: "p2",
    slug: "stonewashed-linen-sheet-set",
    name: "Stonewashed Linen Sheet Set",
    category_slug: "bedroom",
    short_description: "Garment-washed European flax with a lived-in softness.",
    description:
      "Our signature linen is stonewashed for a soft, tumbled texture from the very first night. Naturally temperature-regulating, it keeps you cool in the heat and cosy in the cold.",
    material: "100% European flax linen, stonewashed",
    details: [
      "Pre-washed for zero shrinkage surprises",
      "Naturally breathable and moisture-wicking",
      "Yarn-dyed for rich, lasting colour",
    ],
    care: ["Machine wash warm", "Line dry or tumble dry low", "No ironing needed"],
    colors: ["Natural", "Terracotta", "Charcoal"],
    images: [u("1595526114035-0d45ed16cfbf"), u("1522771739844-6a9f6d5f14af")],
    sizes: [
      { name: "Double", dimensions: "200 × 220 cm", price: 19500, compare_at_price: null },
      { name: "Queen", dimensions: "230 × 250 cm", price: 22500, compare_at_price: null },
      { name: "King", dimensions: "260 × 270 cm", price: 25500, compare_at_price: null },
    ],
    badge: null,
    featured: true,
    in_stock: true,
  },
  {
    id: "p3",
    slug: "signature-sateen-fitted-sheet",
    name: "Signature Sateen Fitted Sheet",
    category_slug: "bedroom",
    short_description: "Buttery-smooth sateen with a subtle lustre.",
    description:
      "A silky-soft fitted sheet in our signature sateen weave. The full elastic hem and extra-deep pocket keep it perfectly in place on mattresses up to 40 cm.",
    material: "100% long-staple cotton, 300 thread count sateen",
    details: ["Extra-deep 40 cm pocket", "Full elastic hem", "Silky sateen finish"],
    care: ["Machine wash cold", "Tumble dry low"],
    colors: ["Ivory", "Stone", "Dusk Blue"],
    images: [u("1505693416388-ac5ce068fe85"), u("1631049035182-249067d7618e")],
    sizes: [
      { name: "Single", dimensions: "90 × 200 cm", price: 6500, compare_at_price: null },
      { name: "Double", dimensions: "140 × 200 cm", price: 7900, compare_at_price: null },
      { name: "Queen", dimensions: "160 × 200 cm", price: 8900, compare_at_price: null },
      { name: "King", dimensions: "180 × 200 cm", price: 9900, compare_at_price: null },
    ],
    badge: null,
    featured: false,
    in_stock: true,
  },
  {
    id: "p4",
    slug: "terracotta-linen-duvet-set",
    name: "Terracotta Linen Duvet Set",
    category_slug: "bedroom",
    short_description: "Sun-baked terracotta linen, hand-finished with ties.",
    description:
      "The set from our campaign imagery. Deep terracotta linen, stonewashed to a soft slub texture and finished with hand-tied corner closures that keep your duvet exactly where it should be.",
    material: "100% European flax linen, stonewashed",
    details: [
      "Includes duvet cover and two pillowcases",
      "Hand-tied closures, interior corner ties",
      "Dyed in small batches for depth of colour",
    ],
    care: ["Machine wash warm", "Line dry", "No ironing needed"],
    colors: ["Terracotta", "Ochre"],
    images: [u("1616594039964-ae9021a400a0"), u("1586023492125-27b2c045efd7")],
    sizes: [
      { name: "Double", dimensions: "200 × 200 cm", price: 24500, compare_at_price: null },
      { name: "Queen", dimensions: "225 × 220 cm", price: 27500, compare_at_price: null },
      { name: "King", dimensions: "245 × 240 cm", price: 29500, compare_at_price: null },
    ],
    badge: "Bestseller",
    featured: true,
    in_stock: true,
  },
  {
    id: "p5",
    slug: "cloud-white-duvet-cover",
    name: "Cloud White Duvet Cover",
    category_slug: "bedroom",
    short_description: "Hotel-crisp white percale with an invisible button placket.",
    description:
      "The five-star hotel look, made for home. Crisp white percale with a hidden button placket and interior ties. Bleach-friendly and built for years of washing.",
    material: "100% long-staple cotton, 400 thread count percale",
    details: ["Hidden button placket", "Interior duvet ties", "Bleach-friendly pure white"],
    care: ["Machine wash warm", "Tumble dry medium", "Iron for a crisp finish"],
    colors: ["Cloud White"],
    images: [u("1618773928121-c32242e63f39"), u("1522771739844-6a9f6d5f14af")],
    sizes: [
      { name: "Double", dimensions: "200 × 200 cm", price: 16500, compare_at_price: null },
      { name: "Queen", dimensions: "225 × 220 cm", price: 18500, compare_at_price: null },
      { name: "King", dimensions: "245 × 240 cm", price: 20500, compare_at_price: null },
    ],
    badge: null,
    featured: true,
    in_stock: true,
  },
  {
    id: "p6",
    slug: "midnight-sateen-duvet-cover",
    name: "Midnight Sateen Duvet Cover",
    category_slug: "bedroom",
    short_description: "Deep navy sateen with a soft, moody sheen.",
    description:
      "A statement cover in deep midnight navy. The sateen weave catches low light beautifully, and the colour is yarn-dyed so it stays rich wash after wash.",
    material: "100% long-staple cotton, 300 thread count sateen",
    details: ["Yarn-dyed midnight navy", "Hidden button placket", "Interior duvet ties"],
    care: ["Machine wash cold, dark cycle", "Tumble dry low"],
    colors: ["Midnight", "Graphite"],
    images: [u("1540518614846-7eded433c457"), u("1578683010236-d716f9a3f461")],
    sizes: [
      { name: "Double", dimensions: "200 × 200 cm", price: 17500, compare_at_price: null },
      { name: "Queen", dimensions: "225 × 220 cm", price: 19500, compare_at_price: null },
      { name: "King", dimensions: "245 × 240 cm", price: 21500, compare_at_price: null },
    ],
    badge: null,
    featured: false,
    in_stock: true,
  },
  {
    id: "p7",
    slug: "heirloom-linen-pillowcase-pair",
    name: "Heirloom Linen Pillowcase Pair",
    category_slug: "bedroom",
    short_description: "A pair of stonewashed linen cases with hand-tied bows.",
    description:
      "Sewn one pair at a time, these linen pillowcases close with hand-tied bows — the small detail our customers photograph most. Soft, breathable and kind to skin and hair.",
    material: "100% European flax linen, stonewashed",
    details: ["Sold as a pair", "Hand-tied bow closure", "Naturally hypoallergenic"],
    care: ["Machine wash warm", "Line dry", "No ironing needed"],
    colors: ["Natural", "Cloud White", "Terracotta"],
    images: [u("1631049552057-403cdb8f0658"), u("1631049307264-da0ec9d70304")],
    sizes: [
      { name: "Standard", dimensions: "50 × 75 cm", price: 6900, compare_at_price: null },
      { name: "King", dimensions: "50 × 90 cm", price: 7900, compare_at_price: null },
    ],
    badge: "New",
    featured: true,
    in_stock: true,
  },
  {
    id: "p8",
    slug: "velvet-touch-pillow-shams",
    name: "Velvet Touch Pillow Shams",
    category_slug: "bedroom",
    short_description: "Brushed cotton shams with a 5 cm flanged border.",
    description:
      "Brushed for a peach-soft hand feel, these shams frame your pillows with a tailored 5 cm flange. The envelope back keeps inserts hidden and secure.",
    material: "100% brushed cotton",
    details: ["Sold as a pair", "5 cm flanged border", "Envelope closure"],
    care: ["Machine wash cold", "Tumble dry low"],
    colors: ["Stone", "Blush", "Moss"],
    images: [u("1615874959474-d609969a20ed"), u("1560185893-a55cbc8c57e8")],
    sizes: [
      { name: "Standard", dimensions: "50 × 75 cm", price: 8500, compare_at_price: null },
      { name: "Euro", dimensions: "65 × 65 cm", price: 9500, compare_at_price: null },
    ],
    badge: null,
    featured: false,
    in_stock: true,
  },
  {
    id: "p9",
    slug: "ivory-homez-signature-bedding-set",
    name: "Ivory Homez Signature Bedding Set",
    category_slug: "bedroom",
    short_description: "The complete Ivory Homez bed — save 20% over unit prices.",
    description:
      "Everything your bed needs in one box: flat sheet, fitted sheet, duvet cover and four pillowcases in our signature percale. Curated to match, priced to save — 20% less than buying each piece alone.",
    material: "100% long-staple cotton, 400 thread count percale",
    details: [
      "7-piece set: flat, fitted, duvet cover, four pillowcases",
      "Save 20% versus unit prices",
      "Gift-ready cotton keeper bag",
    ],
    care: ["Machine wash cold", "Tumble dry low"],
    colors: ["Cloud White", "Oat", "Terracotta"],
    images: [u("1560185893-a55cbc8c57e8"), u("1586023492125-27b2c045efd7")],
    sizes: [
      { name: "Double", dimensions: "7-piece set", price: 36500, compare_at_price: 45500 },
      { name: "Queen", dimensions: "7-piece set", price: 39500, compare_at_price: 49500 },
      { name: "King", dimensions: "7-piece set", price: 42500, compare_at_price: 53000 },
    ],
    badge: "Save 20%",
    featured: true,
    in_stock: true,
  },
  {
    id: "p10",
    slug: "hotel-luxe-bedding-set",
    name: "Hotel Luxe Bedding Set",
    category_slug: "bedroom",
    short_description: "The five-star turn-down, boxed for home.",
    description:
      "Developed with our hospitality partners, the Hotel Luxe set brings the five-star turn-down home: crisp white percale with a tailored double-stitch border, built to survive commercial laundering.",
    material: "100% long-staple cotton, 400 thread count percale",
    details: [
      "5-piece set: flat, fitted, duvet cover, two pillowcases",
      "Commercial-laundry tested",
      "Double-stitched hotel border",
    ],
    care: ["Machine wash warm", "Tumble dry medium", "Bleach-friendly"],
    colors: ["Cloud White"],
    images: [u("1611892440504-42a792e24d32"), u("1571508601891-ca5e7a713859")],
    sizes: [
      { name: "Queen", dimensions: "5-piece set", price: 32500, compare_at_price: null },
      { name: "King", dimensions: "5-piece set", price: 35500, compare_at_price: null },
    ],
    badge: null,
    featured: true,
    in_stock: true,
  },
  {
    id: "p11",
    slug: "handloom-cotton-throw",
    name: "Handloom Cotton Throw",
    category_slug: "lounge",
    short_description: "Handwoven on wooden looms with knotted fringe.",
    description:
      "Each throw is handwoven on traditional wooden looms, then finished with a hand-knotted fringe. Perfect at the foot of the bed or over the shoulder on cool evenings.",
    material: "100% handloom cotton",
    details: ["Handwoven, small-batch", "Hand-knotted fringe", "Ethically made in Sri Lanka"],
    care: ["Gentle machine wash cold", "Line dry"],
    colors: ["Natural Stripe", "Clay Stripe"],
    images: [u("1519710164239-da123dc03ef4"), u("1560185127-6ed189bf02f4")],
    sizes: [{ name: "One Size", dimensions: "130 × 180 cm", price: 9800, compare_at_price: null }],
    badge: null,
    featured: false,
    in_stock: true,
  },
  {
    id: "p12",
    slug: "waffle-weave-blanket",
    name: "Waffle Weave Blanket",
    category_slug: "lounge",
    short_description: "Airy honeycomb weave that layers beautifully.",
    description:
      "The honeycomb structure traps air for warmth without weight. Layer it under a duvet in the cold months or use it alone in the warm ones.",
    material: "100% combed cotton waffle weave",
    details: ["Lightweight, breathable warmth", "Pre-washed for softness", "Selvedge edge finish"],
    care: ["Machine wash cold", "Tumble dry low"],
    colors: ["Oat", "Stone", "Sage"],
    images: [u("1567016432779-094069958ea5"), u("1505691938895-1758d7feb511")],
    sizes: [
      { name: "Double", dimensions: "200 × 220 cm", price: 13500, compare_at_price: null },
      { name: "King", dimensions: "240 × 260 cm", price: 15500, compare_at_price: null },
    ],
    badge: null,
    featured: false,
    in_stock: true,
  },
  {
    id: "p13",
    slug: "washed-linen-apron",
    name: "Washed Linen Apron",
    category_slug: "kitchen",
    short_description: "Artisanal cross-back linen apron with deep front pockets.",
    description:
      "Sewn from heavy European flax linen, this cross-back apron distributes weight evenly across your shoulders, not your neck. Features double-stitched utility pockets and a relaxed, lived-in drape that only gets better with wash and wear.",
    material: "100% European flax linen, washed finish",
    details: [
      "Comfortable cross-back design (no neck ties)",
      "Two deep front utility pockets",
      "Reinforced stitching at stress points",
      "One size fits most",
    ],
    care: ["Machine wash warm", "Tumble dry low", "No ironing needed"],
    colors: ["Oatmeal", "Charcoal", "Sage"],
    images: [u("1556910103001-cf37a8c24207"), u("1590794056226-79ef3a8147e1")],
    sizes: [{ name: "One Size", dimensions: "85 × 90 cm", price: 8500, compare_at_price: null }],
    badge: "New",
    featured: true,
    in_stock: true,
  },
  {
    id: "p14",
    slug: "waffle-kitchen-towels",
    name: "Waffle Kitchen Towels (Set of 3)",
    category_slug: "kitchen",
    short_description: "Thirsty honeycomb kitchen towels in earthy neutrals.",
    description:
      "A pack of three highly absorbent, waffle-woven kitchen towels. Woven from a durable cotton-linen blend that dries quickly and leaves no lint on glassware. Finished with a woven hanging loop.",
    material: "80% long-staple cotton, 20% European linen",
    details: [
      "Set of three matching towels",
      "Quick-drying honeycomb waffle weave",
      "Lint-free drying for glassware",
      "Integrated hanging loop",
    ],
    care: ["Machine wash warm", "Tumble dry medium"],
    colors: ["Natural Mix", "Sage Mix"],
    images: [u("1607344645866-009c320c5ab8"), u("1607344646505-0e7b41cfba45")],
    sizes: [{ name: "Standard Pack", dimensions: "45 × 65 cm (x3)", price: 5900, compare_at_price: null }],
    badge: null,
    featured: false,
    in_stock: true,
  },
  {
    id: "p15",
    slug: "organic-bath-towels",
    name: "Plush Organic Cotton Bath Towels",
    category_slug: "bathroom",
    short_description: "Extra-plush combed cotton towels woven to 700 GSM.",
    description:
      "Wrap yourself in pure luxury. Our organic cotton bath towels are combed for softness and woven to a substantial 700 GSM for ultimate absorbency and warmth. Finished with a clean, classic border.",
    material: "100% organic long-staple cotton, 700 GSM",
    details: [
      "Extra-thick and highly absorbent",
      "GOTS certified organic cotton",
      "Fade-resistant, low-lint weave",
      "Sold individually or as a pair",
    ],
    care: ["Machine wash hot with like colors", "Tumble dry high", "Do not use fabric softener"],
    colors: ["Cloud White", "Oat", "Stone"],
    images: [u("1616627561954-252214724e5b"), u("1540555700478-4be289fbecef")],
    sizes: [
      { name: "Bath Towel", dimensions: "70 × 140 cm", price: 9500, compare_at_price: null },
      { name: "Bath Sheet", dimensions: "100 × 150 cm", price: 12500, compare_at_price: null },
    ],
    badge: "Bestseller",
    featured: true,
    in_stock: true,
  },
  {
    id: "p16",
    slug: "waffle-bathrobe",
    name: "Waffle Cotton Bathrobe",
    category_slug: "bathroom",
    short_description: "Lightweight, spa-style waffle bathrobe with waist tie.",
    description:
      "Inspired by the finest boutique hotels, our waffle bathrobe offers a lightweight, breathable cover-up for post-bath relaxation. The honeycomb weave gently exfoliates and dries quickly. Featuring two deep hip pockets and an adjustable tie belt.",
    material: "100% organic cotton, 350 GSM waffle weave",
    details: [
      "Unisex classic kimono silhouette",
      "Adjustable double belt loops for custom fit",
      "Two deep pockets",
      "Pre-shrunk for lasting fit",
    ],
    care: ["Machine wash warm", "Tumble dry low"],
    colors: ["Oat", "Cloud White"],
    images: [u("1556909114-f6e7ad7d3136"), u("1556909181-ed82035af743")],
    sizes: [
      { name: "S/M", dimensions: "Chest 120cm, Length 115cm", price: 18500, compare_at_price: null },
      { name: "L/XL", dimensions: "Chest 135cm, Length 122cm", price: 18500, compare_at_price: null },
    ],
    badge: null,
    featured: false,
    in_stock: true,
  },
  {
    id: "p17",
    slug: "handloom-seat-cushions",
    name: "Handloom Cotton Seat Cushions",
    category_slug: "garden",
    short_description: "Handwoven box cushions with convenient tie-backs.",
    description:
      "Bring comfort and artisan craftsmanship to your garden dining set. These thick box cushions are handwoven on wooden looms from heavy-weight cotton, filled with supportive recycled fibers and finished with secure ties.",
    material: "100% handloom cotton shell, recycled fiber fill",
    details: [
      "Heavy-duty handwoven canvas shell",
      "Tufted details for shape retention",
      "Two robust tie-backs for secure fastening",
      "Ethically crafted by artisans",
    ],
    care: ["Spot clean only", "Store indoors when not in use", "Air dry thoroughly"],
    colors: ["Natural Stripe", "Sage Stripe", "Charcoal Stripe"],
    images: [u("1600585154340-be6161a56a0c"), u("1600585154526-7ee658dfa8e4")],
    sizes: [{ name: "One Size", dimensions: "40 × 40 × 8 cm", price: 6800, compare_at_price: null }],
    badge: "New",
    featured: true,
    in_stock: true,
  },
  {
    id: "p18",
    slug: "patio-waffle-throw",
    name: "Textured Patio Throw",
    category_slug: "garden",
    short_description: "Durable, wind-resistant thick cotton throw for patio evenings.",
    description:
      "A heavier-weight waffle weave designed specifically for outdoor living. This blanket keeps out the evening chill on the terrace while remaining fully breathable. Finished with a modern self-fringed edge.",
    material: "100% durable long-staple cotton",
    details: [
      "Heavier 480 GSM weight for wind resistance",
      "Fray-resistant self-fringed edges",
      "Generously sized for sharing",
      "Fade-resistant yarn dyeing",
    ],
    care: ["Machine wash cold", "Tumble dry low", "Do not bleach"],
    colors: ["Clay", "Sage", "Charcoal"],
    images: [u("1519710164239-da123dc03ef4"), u("1567016432779-094069958ea5")],
    sizes: [{ name: "One Size", dimensions: "150 × 200 cm", price: 11500, compare_at_price: null }],
    badge: null,
    featured: false,
    in_stock: true,
  },
  {
    id: "p19",
    slug: "heavy-linen-storage",
    name: "Heavy Linen Storage Baskets",
    category_slug: "garage",
    short_description: "Structured storage baskets with natural leather handles.",
    description:
      "Keep utility rooms, pantries and mudrooms organized. Sewn from double-layered heavy linen canvas, these storage baskets stand upright on their own and fold flat when not in use. Finished with double-riveted tan leather handles.",
    material: "100% heavy linen canvas, genuine leather handles",
    details: [
      "Stands upright independently",
      "Double-riveted top-grain leather handles",
      "Collapsible design for easy storage",
      "Neutral linen texture hides dust",
    ],
    care: ["Wipe clean with a damp cloth", "Do not submerge leather handles in water"],
    colors: ["Natural Linen", "Charcoal Linen"],
    images: [u("1532882772249-df68a5dffc3e"), u("1522771739844-6a9f6d5f14af")],
    sizes: [
      { name: "Medium", dimensions: "30 × 30 × 30 cm", price: 7900, compare_at_price: null },
      { name: "Large", dimensions: "40 × 40 × 40 cm", price: 9800, compare_at_price: null },
    ],
    badge: "New",
    featured: true,
    in_stock: true,
  },
  {
    id: "p20",
    slug: "canvas-utility-organizer",
    name: "Canvas Utility Hanging Organizer",
    category_slug: "garage",
    short_description: "Wall-mounted heavy canvas pocket organizer with brass grommets.",
    description:
      "A premium solution for organizing small tools, garden shears and utility accessories. Woven from 18oz heavy waxed cotton canvas, this hanging organizer features 8 pockets of varying sizes and reinforced brass hanging grommets.",
    material: "100% waxed cotton canvas, brass grommets",
    details: [
      "8 structured pockets (4 small, 4 large)",
      "Three reinforced brass hanging grommets",
      "Water-resistant waxed finish",
      "Perfect for garage, workshop, or greenhouse walls",
    ],
    care: ["Wipe clean only", "Do not wash or dry clean (wax finish)"],
    colors: ["Olive", "Oatmeal"],
    images: [u("1581235720704-06d3acfcb36f"), u("1590794056226-79ef3a8147e1")],
    sizes: [{ name: "Standard", dimensions: "50 × 80 cm", price: 11000, compare_at_price: null }],
    badge: null,
    featured: false,
    in_stock: true,
  },
];
