import type { Category, Product } from "./types";

/**
 * Enivrant demo catalog — six maison collections, 36 pieces.
 *
 * Imagery is first-party: every photograph was generated for this brand and
 * lives under /public/images (categories, banners, products). Local paths mean
 * next/image optimises them without any remote host allowlist.
 */

/** Product photograph pair: `-a` is the studio shot, `-b` the lifestyle detail. */
const shots = (slug: string) => [
  `/images/products/${slug}-a.webp`,
  `/images/products/${slug}-b.webp`,
];

export const seedCategories: Category[] = [
  {
    id: "c1",
    slug: "wellness",
    name: "Luxury Wellness & Self-Care",
    description:
      "Bath rituals, botanical oils and slow-evening essentials — the art of taking your time.",
    image: "/images/categories/wellness-self-care.webp",
    sort_order: 1,
  },
  {
    id: "c2",
    slug: "fragrances",
    name: "Fragrances & Perfume",
    description:
      "Eaux de parfum, diffusers and candles composed around jasmine, Ceylon tea, oud and sandalwood.",
    image: "/images/categories/fragrances-perfume.webp",
    sort_order: 2,
  },
  {
    id: "c3",
    slug: "home-living",
    name: "Home & Living Elegance",
    description:
      "Hand-thrown stoneware, rattan light, solid teak and travertine — quiet luxury for every room.",
    image: "/images/categories/home-living.webp",
    sort_order: 3,
  },
  {
    id: "c4",
    slug: "jewelry",
    name: "Pearls & Fine Jewelry",
    description:
      "Freshwater pearls, Ceylon sapphires and gold vermeil, strung and set by hand in our atelier.",
    image: "/images/categories/pearls-fine-jewelry.webp",
    sort_order: 4,
  },
  {
    id: "c5",
    slug: "fashion",
    name: "Fashion & Accessories",
    description:
      "Washed linen, hand-painted batik silk, woven palmyrah and vegetable-tanned leather.",
    image: "/images/categories/fashion-accessories.webp",
    sort_order: 5,
  },
  {
    id: "c6",
    slug: "bedlinen",
    name: "Fine Bedlinen & Sleep Luxury",
    description:
      "Percale, stonewashed linen, mulberry silk and down — everything the best night of your week needs.",
    image: "/images/categories/bedlinen-sleep.webp",
    sort_order: 6,
  },
];

export const seedProducts: Product[] = [
  // ── Luxury Wellness & Self-Care ────────────────────────────────────────
  {
    id: "p1",
    slug: "ceylon-bath-soak-ritual-set",
    name: "Ceylon Bath Soak Ritual Set",
    category_slug: "wellness",
    short_description: "Himalayan salt, jasmine petals and cinnamon bark, in apothecary glass.",
    description:
      "Two hand-filled apothecary jars of pink Himalayan salt folded through dried jasmine petals and slivers of Ceylon cinnamon bark. A single scoop turns a bath into an hour you actually look forward to — the salt softens the water, the jasmine perfumes the steam.",
    material: "Pink Himalayan salt, dried jasmine, Ceylon cinnamon bark",
    details: [
      "Two 450 g apothecary jars with cork lids",
      "Hand-blended and hand-filled in small batches",
      "Includes a turned beechwood scoop",
      "No synthetic fragrance, colour or foaming agents",
    ],
    care: ["Keep the lid sealed and the jar dry", "Use within 12 months of opening"],
    colors: ["Blush", "Ivory"],
    images: shots("ceylon-bath-soak-ritual-set"),
    sizes: [
      { name: "Duo set", dimensions: "2 × 450 g", price: 9800, compare_at_price: null },
      { name: "Grand set", dimensions: "4 × 450 g", price: 17500, compare_at_price: 19600 },
    ],
    badge: "Bestseller",
    featured: true,
    in_stock: true,
  },
  {
    id: "p2",
    slug: "frangipani-body-oil",
    name: "Frangipani Body Oil",
    category_slug: "wellness",
    short_description: "A golden, fast-absorbing oil of coconut, sesame and frangipani.",
    description:
      "Cold-pressed virgin coconut and sesame oils infused with frangipani blossoms picked at dawn. It sinks in rather than sitting on the skin, and leaves the faintest trace of the flower behind — best applied while you are still damp from the bath.",
    material: "Virgin coconut oil, sesame oil, frangipani absolute, vitamin E",
    details: [
      "100 ml frosted glass bottle with a brushed-gold pump",
      "Cold-pressed, unrefined base oils",
      "Non-greasy, fast-absorbing finish",
      "Free of mineral oil, silicones and parabens",
    ],
    care: ["Store away from direct sunlight", "Warm the bottle in your hands in cool weather"],
    colors: ["Champagne"],
    images: shots("frangipani-body-oil"),
    sizes: [
      { name: "100 ml", dimensions: "Full size", price: 7200, compare_at_price: null },
      { name: "30 ml", dimensions: "Travel size", price: 3400, compare_at_price: null },
    ],
    badge: null,
    featured: true,
    in_stock: true,
  },
  {
    id: "p3",
    slug: "rose-quartz-facial-ritual-set",
    name: "Rose Quartz Facial Ritual Set",
    category_slug: "wellness",
    short_description: "A gua sha stone and roller cut from genuine rose quartz.",
    description:
      "Cut and polished from a single seam of rose quartz, then finished with gold-tone fittings. Cool to the touch on the hottest afternoon — five minutes of slow, upward strokes at the end of the day does more for a tired face than most things in a bottle.",
    material: "Genuine rose quartz, gold-tone brass fittings",
    details: [
      "Gua sha stone and dual-ended facial roller",
      "Natural stone — veining and tone vary piece to piece",
      "Silent, snag-free roller bearings",
      "Presented in an ivory linen drawstring pouch",
    ],
    care: ["Wash with mild soap and dry fully", "Chill in the fridge for a cooling ritual"],
    colors: ["Blush", "Gold"],
    images: shots("rose-quartz-facial-ritual-set"),
    sizes: [{ name: "Two-piece set", dimensions: "Roller + gua sha", price: 6400, compare_at_price: null }],
    badge: null,
    featured: false,
    in_stock: true,
  },
  {
    id: "p4",
    slug: "ayurvedic-tea-ritual-box",
    name: "Ayurvedic Tea Ritual Box",
    category_slug: "wellness",
    short_description: "Three single-estate Ceylon blends with a solid brass infuser.",
    description:
      "Three blends drawn from the hill country and the Ayurvedic tradition: a morning black with cardamom, an afternoon green with cornflower, and a caffeine-free evening tisane of tulsi and liquorice. Packed in matte tins with wooden lids, with a solid brass infuser.",
    material: "Single-estate Ceylon tea, botanicals, solid brass infuser",
    details: [
      "Three 60 g tins — Morning, Afternoon, Evening",
      "Loose leaf, whole-leaf grade, never dust",
      "Solid brass infuser with a resting dish",
      "Linen-wrapped gift box, ready to give",
    ],
    care: ["Keep tins sealed and out of sunlight", "Rinse the infuser and dry to keep the shine"],
    colors: ["Ivory", "Gold"],
    images: shots("ayurvedic-tea-ritual-box"),
    sizes: [{ name: "Gift box", dimensions: "3 × 60 g + infuser", price: 8900, compare_at_price: null }],
    badge: "New",
    featured: false,
    in_stock: true,
  },
  {
    id: "p5",
    slug: "waffle-linen-spa-robe",
    name: "Waffle Linen Spa Robe",
    category_slug: "wellness",
    short_description: "Honeycomb linen-cotton that dries fast and only softens.",
    description:
      "Woven in a deep honeycomb waffle from linen and long-staple cotton, so it drinks water without ever feeling heavy. Cut generously with deep patch pockets, a self-tie belt and a hanging loop — the robe you reach for long after the bath is cold.",
    material: "55% European flax linen, 45% long-staple cotton",
    details: [
      "Deep honeycomb waffle weave, pre-washed",
      "Two patch pockets and a self-tie belt",
      "Shawl collar with a reinforced hanging loop",
      "Unisex cut — size down for a closer fit",
    ],
    care: ["Machine wash warm", "Tumble dry low", "No ironing needed"],
    colors: ["Oat", "Ivory"],
    images: shots("waffle-linen-spa-robe"),
    sizes: [
      { name: "S / M", dimensions: "Length 120 cm", price: 13500, compare_at_price: null },
      { name: "L / XL", dimensions: "Length 128 cm", price: 14500, compare_at_price: null },
    ],
    badge: null,
    featured: true,
    in_stock: true,
  },
  {
    id: "p6",
    slug: "silk-sleep-ritual-set",
    name: "Silk Sleep Ritual Set",
    category_slug: "wellness",
    short_description: "22-momme mulberry silk mask, scrunchie and pouch.",
    description:
      "A weighted 22-momme mulberry silk sleep mask that blocks light without pressing on your eyes, with a matching scrunchie that won't crease your hair overnight. Both live in a silk pouch that fits in any bag — the whole set weighs less than a paperback.",
    material: "22-momme grade 6A mulberry silk",
    details: [
      "Contoured mask with a soft elastic strap",
      "Matching scrunchie and travel pouch",
      "Naturally hypoallergenic and temperature-regulating",
      "Hand-rolled edges throughout",
    ],
    care: ["Hand wash cold with a pH-neutral soap", "Dry flat away from sunlight"],
    colors: ["Champagne", "Ivory"],
    images: shots("silk-sleep-ritual-set"),
    sizes: [{ name: "Three-piece set", dimensions: "Mask, scrunchie, pouch", price: 9600, compare_at_price: 12000 }],
    badge: "Save 20%",
    featured: true,
    in_stock: true,
  },

  // ── Fragrances & Perfume ───────────────────────────────────────────────
  {
    id: "p7",
    slug: "enivrant-no-1-eau-de-parfum",
    name: "Enivrant No. 1 Eau de Parfum",
    category_slug: "fragrances",
    short_description: "Ceylon cinnamon, cedar and amber — the house signature.",
    description:
      "The scent the maison is named for. It opens warm and dry with Ceylon cinnamon bark and bergamot, settles into cedar and orris through the afternoon, and finishes on amber and a whisper of vanilla against your skin at night. 22% concentration — one press lasts the day.",
    material: "Eau de parfum, 22% concentration",
    details: [
      "Top: Ceylon cinnamon bark, bergamot, pink pepper",
      "Heart: cedarwood, orris root, jasmine absolute",
      "Base: amber, tonka bean, vanilla",
      "Eight to ten hours of wear; unisex composition",
    ],
    care: ["Store upright, away from heat and light", "Spray onto skin, never rub in"],
    colors: ["Champagne", "Gold"],
    images: shots("enivrant-no-1-eau-de-parfum"),
    sizes: [
      { name: "50 ml", dimensions: "Signature bottle", price: 26500, compare_at_price: null },
      { name: "100 ml", dimensions: "Grand format", price: 38500, compare_at_price: null },
      { name: "10 ml", dimensions: "Purse atomiser", price: 8500, compare_at_price: null },
    ],
    badge: "Bestseller",
    featured: true,
    in_stock: true,
  },
  {
    id: "p8",
    slug: "jasmine-nocturne-eau-de-parfum",
    name: "Jasmine Nocturne Eau de Parfum",
    category_slug: "fragrances",
    short_description: "Night-picked jasmine sambac over white musk.",
    description:
      "Jasmine sambac picked after dark, when the flower gives up the most of itself, laid over a base of white musk and sandalwood. Softer and more intimate than the No. 1 — it sits close to the skin rather than announcing itself across a room.",
    material: "Eau de parfum, 18% concentration",
    details: [
      "Top: jasmine sambac, neroli, pear",
      "Heart: tuberose, ylang-ylang, rose de mai",
      "Base: white musk, sandalwood, benzoin",
      "Six to eight hours of wear; fluted glass stopper",
    ],
    care: ["Store upright, away from heat and light", "Spray onto skin, never rub in"],
    colors: ["Blush", "Ivory"],
    images: shots("jasmine-nocturne-eau-de-parfum"),
    sizes: [
      { name: "50 ml", dimensions: "Signature bottle", price: 24500, compare_at_price: null },
      { name: "100 ml", dimensions: "Grand format", price: 35500, compare_at_price: null },
    ],
    badge: null,
    featured: true,
    in_stock: true,
  },
  {
    id: "p9",
    slug: "discovery-set-five-scents",
    name: "Discovery Set — Five Scents",
    category_slug: "fragrances",
    short_description: "The whole library in 8 ml vials. Credited against your first bottle.",
    description:
      "Five 8 ml atomisers holding the full house library, nested in ivory satin. Live with each one for a week before you commit — and the price of the set is credited in full against your first full bottle, so trying costs you nothing in the end.",
    material: "Eau de parfum, five compositions",
    details: [
      "Five 8 ml glass atomisers with gold caps",
      "No. 1, Jasmine Nocturne, Oud Rose, Ceylon Tea, Sea Salt",
      "About 100 sprays per vial",
      "Value credited against your first full bottle",
    ],
    care: ["Store upright, away from heat and light"],
    colors: ["Ivory", "Gold"],
    images: shots("discovery-set-five-scents"),
    sizes: [{ name: "Five vials", dimensions: "5 × 8 ml", price: 11500, compare_at_price: null }],
    badge: "New",
    featured: true,
    in_stock: true,
  },
  {
    id: "p10",
    slug: "ceylon-tea-vetiver-reed-diffuser",
    name: "Ceylon Tea & Vetiver Reed Diffuser",
    category_slug: "fragrances",
    short_description: "Black tea and damp vetiver, in matte cream stoneware.",
    description:
      "The smell of a tea factory at dawn — dry black leaf, damp earth, a little smoke — held in a matte stoneware vessel that looks like nothing and suits everything. Twelve rattan reeds, three to four months of quiet diffusion in a normal-sized room.",
    material: "Matte stoneware vessel, natural rattan reeds, alcohol-free base",
    details: [
      "200 ml, with twelve natural rattan reeds",
      "Three to four months in a 20 m² room",
      "Alcohol-free, low-evaporation base",
      "Refillable — the vessel is made to keep",
    ],
    care: ["Turn the reeds weekly", "Keep off polished or painted surfaces"],
    colors: ["Cream", "Natural"],
    images: shots("ceylon-tea-vetiver-reed-diffuser"),
    sizes: [
      { name: "200 ml", dimensions: "With 12 reeds", price: 9200, compare_at_price: null },
      { name: "Refill 200 ml", dimensions: "Liquid only", price: 5400, compare_at_price: null },
    ],
    badge: null,
    featured: false,
    in_stock: true,
  },
  {
    id: "p11",
    slug: "sandalwood-sea-salt-candle",
    name: "Sandalwood & Sea Salt Candle",
    category_slug: "fragrances",
    short_description: "Coconut-soy wax in a stoneware vessel you'll keep.",
    description:
      "Creamy sandalwood cut with mineral sea salt and a thread of driftwood — warm without being sweet. Poured by hand into a speckled stoneware vessel with a turned wooden lid, and a cotton wick that burns clean to the very edge.",
    material: "Coconut-soy wax, cotton wick, stoneware vessel, wooden lid",
    details: [
      "280 g, roughly 55 hours of burn time",
      "Coconut-soy blend — no paraffin, no soot",
      "Hand-thrown speckled stoneware vessel with wooden lid",
      "Phthalate-free fragrance oils",
    ],
    care: ["Trim the wick to 5 mm before each burn", "First burn: let the full surface melt"],
    colors: ["Cream", "Natural"],
    images: shots("sandalwood-sea-salt-candle"),
    sizes: [
      { name: "280 g", dimensions: "Single wick", price: 6800, compare_at_price: null },
      { name: "Trio", dimensions: "3 × 280 g", price: 18400, compare_at_price: 20400 },
    ],
    badge: null,
    featured: false,
    in_stock: true,
  },
  {
    id: "p12",
    slug: "oud-rose-solid-perfume",
    name: "Oud & Rose Solid Perfume",
    category_slug: "fragrances",
    short_description: "A balm of oud and Damask rose in a refillable gold tin.",
    description:
      "Beeswax, jojoba and shea whipped with oud and Damask rose absolute into a balm you warm with a fingertip. It travels through any security line, never spills in a bag, and sits closer to the skin than a spray ever does.",
    material: "Beeswax, jojoba, shea butter, oud and rose absolute",
    details: [
      "15 g brushed-gold refillable tin",
      "Alcohol-free — kind to sensitive skin",
      "Cabin-bag friendly, spill-proof",
      "Presented in an ivory linen pouch",
    ],
    care: ["Close the lid firmly after use", "Keep below 30°C so the balm stays firm"],
    colors: ["Gold", "Blush"],
    images: shots("oud-rose-solid-perfume"),
    sizes: [{ name: "15 g", dimensions: "Refillable tin", price: 7400, compare_at_price: null }],
    badge: null,
    featured: false,
    in_stock: true,
  },

  // ── Home & Living Elegance ─────────────────────────────────────────────
  {
    id: "p13",
    slug: "glazed-stoneware-dinner-set",
    name: "Glazed Stoneware Dinner Set",
    category_slug: "home-living",
    short_description: "Hand-thrown stoneware in a speckled, small-batch glaze.",
    description:
      "Thrown on the wheel and glazed in small batches, so no two pieces are quite alike — and that is the point. Generous plates, deep bowls and mugs that hold their heat, all fired high enough to survive the dishwasher and a decade of Sundays.",
    material: "Hand-thrown stoneware, lead-free speckled glaze",
    details: [
      "12-piece set: 4 plates, 4 bowls, 4 mugs",
      "Each piece thrown and glazed by hand",
      "Dishwasher and microwave safe",
      "Chip-resistant high-fire stoneware",
    ],
    care: ["Dishwasher safe on a normal cycle", "Avoid thermal shock — no oven-to-fridge"],
    colors: ["Cream", "Sage"],
    images: shots("glazed-stoneware-dinner-set"),
    sizes: [
      { name: "12-piece set", dimensions: "4 place settings", price: 24500, compare_at_price: null },
      { name: "18-piece set", dimensions: "6 place settings", price: 34500, compare_at_price: null },
    ],
    badge: null,
    featured: true,
    in_stock: true,
  },
  {
    id: "p14",
    slug: "rattan-pendant-light",
    name: "Rattan Pendant Light",
    category_slug: "home-living",
    short_description: "Hand-woven rattan that turns light into texture.",
    description:
      "Woven from natural rattan over a solid brass fitting, this pendant throws a warm lattice of light and shadow across a room. Hang it low over a dining table or in a reading corner — it is the piece that makes the evening.",
    material: "Hand-woven natural rattan, solid brass fitting",
    details: [
      "Casts a warm, patterned lattice of light",
      "1.5 m adjustable cord and ceiling rose included",
      "Fits a standard E27 bulb (not included)",
      "Each shade woven by hand — patterns vary slightly",
    ],
    care: ["Dust with a dry cloth or soft brush", "Indoor use only"],
    colors: ["Natural", "Oat"],
    images: shots("rattan-pendant-light"),
    sizes: [
      { name: "Medium", dimensions: "Ø 40 cm", price: 14500, compare_at_price: null },
      { name: "Large", dimensions: "Ø 55 cm", price: 18500, compare_at_price: null },
    ],
    badge: "New",
    featured: true,
    in_stock: true,
  },
  {
    id: "p15",
    slug: "hand-thrown-ceramic-vase",
    name: "Hand-Thrown Ceramic Vase",
    category_slug: "home-living",
    short_description: "Wheel-thrown stoneware with a quiet matte glaze.",
    description:
      "Thrown on the wheel in our atelier, each vase carries the maker's finger lines beneath a quiet matte glaze. Weighted at the base to hold a full branch without tipping — or to stand beautifully empty, which is how we keep ours.",
    material: "Wheel-thrown stoneware, matte glaze",
    details: [
      "Each piece is one of one — glaze and lines vary",
      "Watertight, fully sealed interior",
      "Weighted base holds tall stems",
      "Fired to 1,240°C for strength",
    ],
    care: ["Rinse and hand dry", "Avoid abrasive scrubbing on the glaze"],
    colors: ["Cream", "Ivory"],
    images: shots("hand-thrown-ceramic-vase"),
    sizes: [
      { name: "Small", dimensions: "H 18 cm", price: 4900, compare_at_price: null },
      { name: "Medium", dimensions: "H 26 cm", price: 6900, compare_at_price: null },
      { name: "Large", dimensions: "H 34 cm", price: 8900, compare_at_price: null },
    ],
    badge: null,
    featured: false,
    in_stock: true,
  },
  {
    id: "p16",
    slug: "teak-bedside-table",
    name: "Teak Bedside Table",
    category_slug: "home-living",
    short_description: "Solid teak, hand-cut joinery, oiled never lacquered.",
    description:
      "A quiet piece of furniture that earns its place: solid Sri Lankan teak, hand-cut joinery with no visible fixings, and a lower shelf for the book you are actually reading. Oiled rather than lacquered, so the grain keeps breathing and deepens with the years.",
    material: "Solid teak, hand-oiled finish",
    details: [
      "Solid timber throughout — no veneers",
      "Traditional hand-cut joinery, no visible fixings",
      "Lower shelf for books and baskets",
      "Grain and tone vary board to board",
    ],
    care: ["Dust with a dry cloth", "Re-oil yearly", "Keep clear of direct radiator heat"],
    colors: ["Natural", "Tan"],
    images: shots("teak-bedside-table"),
    sizes: [{ name: "One size", dimensions: "45 × 35 × 55 cm", price: 16500, compare_at_price: null }],
    badge: null,
    featured: false,
    in_stock: true,
  },
  {
    id: "p17",
    slug: "handloom-cotton-throw",
    name: "Handloom Cotton Throw",
    category_slug: "home-living",
    short_description: "Handwoven on wooden looms with a knotted fringe.",
    description:
      "Each throw is woven on a traditional wooden loom by one weaver from start to finish, then finished with a hand-knotted fringe. Light enough for a warm evening, wide enough to share — it lives on the arm of the sofa and ends up over someone's knees.",
    material: "100% handloom cotton",
    details: [
      "Handwoven in small batches, one weaver per piece",
      "Hand-knotted fringe on both ends",
      "Pre-washed for softness and zero shrinkage",
      "Ethically made in Sri Lanka",
    ],
    care: ["Gentle machine wash cold", "Line dry"],
    colors: ["Natural", "Dusty Blue"],
    images: shots("handloom-cotton-throw"),
    sizes: [{ name: "One size", dimensions: "130 × 180 cm", price: 9800, compare_at_price: null }],
    badge: null,
    featured: false,
    in_stock: true,
  },
  {
    id: "p18",
    slug: "travertine-brass-tray",
    name: "Travertine & Brass Tray",
    category_slug: "home-living",
    short_description: "Solid travertine with hand-brushed brass handles.",
    description:
      "Cut from a single slab of Italian travertine and fitted with hand-brushed brass handles. Heavy in the way good things are heavy. It gathers the perfume bottles on a dressing table, or carries two coffees and the morning paper without a wobble.",
    material: "Solid travertine, brushed brass handles",
    details: [
      "Cut from a single slab — veining varies",
      "Hand-brushed solid brass handles",
      "Felt-padded underside protects surfaces",
      "Sealed against water marks",
    ],
    care: ["Wipe with a damp cloth", "Blot spills quickly — stone is porous"],
    colors: ["Ivory", "Gold"],
    images: shots("travertine-brass-tray"),
    sizes: [
      { name: "Medium", dimensions: "30 × 20 cm", price: 11500, compare_at_price: null },
      { name: "Large", dimensions: "40 × 28 cm", price: 15500, compare_at_price: null },
    ],
    badge: null,
    featured: false,
    in_stock: true,
  },

  // ── Pearls & Fine Jewelry ──────────────────────────────────────────────
  {
    id: "p19",
    slug: "freshwater-pearl-strand-necklace",
    name: "Freshwater Pearl Strand Necklace",
    category_slug: "jewelry",
    short_description: "AAA-grade pearls, hand-knotted on silk between each bead.",
    description:
      "Round AAA-grade freshwater pearls, matched by hand for lustre and size, then knotted individually onto silk thread so they never rub and never all scatter. Finished with a solid 14k gold-filled clasp. The necklace you will still be wearing in thirty years.",
    material: "AAA-grade freshwater pearls, silk thread, 14k gold-filled clasp",
    details: [
      "7–8 mm round pearls, hand-matched for lustre",
      "Individually knotted on silk between each pearl",
      "Solid 14k gold-filled clasp, not plated",
      "Presented in a lined jewellery box",
    ],
    care: ["Last on, first off — perfume dulls nacre", "Wipe with a soft cloth", "Store flat, never hanging"],
    colors: ["Pearl White", "Gold"],
    images: shots("freshwater-pearl-strand-necklace"),
    sizes: [
      { name: "Choker 42 cm", dimensions: "7–8 mm pearls", price: 32500, compare_at_price: null },
      { name: "Princess 46 cm", dimensions: "7–8 mm pearls", price: 36500, compare_at_price: null },
      { name: "Matinée 60 cm", dimensions: "7–8 mm pearls", price: 46500, compare_at_price: null },
    ],
    badge: "Bestseller",
    featured: true,
    in_stock: true,
  },
  {
    id: "p20",
    slug: "baroque-pearl-drop-earrings",
    name: "Baroque Pearl Drop Earrings",
    category_slug: "jewelry",
    short_description: "No two alike — baroque pearls on gold vermeil huggies.",
    description:
      "Baroque pearls are the ones the industry once threw away for being irregular; we think they are the interesting ones. Each drop is chosen individually and hung from a gold vermeil huggie hoop, which means the pair you receive is genuinely yours alone.",
    material: "Baroque freshwater pearls, gold vermeil over sterling silver",
    details: [
      "12–15 mm baroque pearls — every shape unique",
      "Gold vermeil over solid sterling silver",
      "Secure hinged huggie closure",
      "Weigh under 4 g each — no dragging on the lobe",
    ],
    care: ["Last on, first off", "Wipe with a soft cloth after wear", "Store in the pouch provided"],
    colors: ["Pearl White", "Gold"],
    images: shots("baroque-pearl-drop-earrings"),
    sizes: [{ name: "One size", dimensions: "Drop 32 mm", price: 18500, compare_at_price: null }],
    badge: null,
    featured: true,
    in_stock: true,
  },
  {
    id: "p21",
    slug: "ceylon-blue-sapphire-pendant",
    name: "Ceylon Blue Sapphire Pendant",
    category_slug: "jewelry",
    short_description: "A Ratnapura sapphire, bezel-set in solid 18k gold.",
    description:
      "An oval Ceylon blue sapphire from the Ratnapura mines — the stone this island is known for — bezel-set in solid 18k yellow gold on a fine cable chain. Certified, traceable, and unheated, which is rarer than most of what you will be shown elsewhere.",
    material: "Ceylon blue sapphire, solid 18k yellow gold",
    details: [
      "1.2 ct oval Ceylon sapphire, unheated",
      "Solid 18k yellow gold bezel and chain",
      "Certificate of origin included",
      "Adjustable 42/45 cm cable chain",
    ],
    care: ["Remove before swimming or sport", "Clean with warm water and a soft brush"],
    colors: ["Sapphire Blue", "Gold"],
    images: shots("ceylon-blue-sapphire-pendant"),
    sizes: [{ name: "One size", dimensions: "1.2 ct, 42/45 cm chain", price: 87500, compare_at_price: null }],
    badge: "Fine jewellery",
    featured: true,
    in_stock: true,
  },
  {
    id: "p22",
    slug: "rainbow-moonstone-ring",
    name: "Rainbow Moonstone Ring",
    category_slug: "jewelry",
    short_description: "A cabochon moonstone with a blue flash, in 14k gold.",
    description:
      "A high-dome rainbow moonstone cabochon that throws a blue flash when it catches the light, bezel-set in solid 14k gold on a slim band. Quiet from across a room and quietly extraordinary up close — which is more or less the house position on everything.",
    material: "Rainbow moonstone, solid 14k yellow gold",
    details: [
      "10 × 8 mm high-dome cabochon",
      "Solid 14k gold bezel and band, not plated",
      "Natural stone — every flash pattern differs",
      "Sizes 6 to 9; free resizing within 30 days",
    ],
    care: ["Remove before swimming or sport", "Moonstone is soft — store separately"],
    colors: ["Moonstone", "Gold"],
    images: shots("rainbow-moonstone-ring"),
    sizes: [
      { name: "Size 6", dimensions: "16.5 mm", price: 42500, compare_at_price: null },
      { name: "Size 7", dimensions: "17.3 mm", price: 42500, compare_at_price: null },
      { name: "Size 8", dimensions: "18.2 mm", price: 42500, compare_at_price: null },
    ],
    badge: null,
    featured: false,
    in_stock: true,
  },
  {
    id: "p23",
    slug: "pearl-gold-vermeil-bracelet",
    name: "Pearl & Gold Vermeil Bracelet",
    category_slug: "jewelry",
    short_description: "Knotted pearls with a gold vermeil lobster clasp.",
    description:
      "The strand necklace's everyday sibling: the same hand-matched freshwater pearls, individually knotted on silk, at a length you can wear with a rolled sleeve. Stack it with a plain gold bangle, or wear it entirely alone.",
    material: "AAA-grade freshwater pearls, silk thread, gold vermeil clasp",
    details: [
      "6–7 mm round pearls, hand-matched",
      "Individually knotted on silk",
      "Gold vermeil lobster clasp with an extender",
      "Presented in a lined jewellery box",
    ],
    care: ["Last on, first off", "Wipe with a soft cloth", "Store flat in the box provided"],
    colors: ["Pearl White", "Gold"],
    images: shots("pearl-gold-vermeil-bracelet"),
    sizes: [
      { name: "17 cm", dimensions: "6–7 mm pearls", price: 14500, compare_at_price: null },
      { name: "19 cm", dimensions: "6–7 mm pearls", price: 15500, compare_at_price: null },
    ],
    badge: null,
    featured: false,
    in_stock: true,
  },
  {
    id: "p24",
    slug: "hammered-gold-vermeil-hoops",
    name: "Hammered Gold Vermeil Hoops",
    category_slug: "jewelry",
    short_description: "Hand-hammered hoops that catch light from every angle.",
    description:
      "Each hoop is hammered by hand, so the surface breaks the light into dozens of small flashes instead of one flat shine. Thick gold vermeil over sterling silver — the plating is measured in microns, not molecules, and it will not wear through.",
    material: "2.5 micron gold vermeil over sterling silver",
    details: [
      "Hand-hammered — every hoop's texture is unique",
      "2.5 micron vermeil, far above plating standard",
      "Secure hinged closure",
      "Hypoallergenic, nickel-free",
    ],
    care: ["Remove before showering", "Polish with the cloth provided"],
    colors: ["Gold"],
    images: shots("hammered-gold-vermeil-hoops"),
    sizes: [
      { name: "Small", dimensions: "Ø 20 mm", price: 9800, compare_at_price: null },
      { name: "Medium", dimensions: "Ø 30 mm", price: 11500, compare_at_price: null },
      { name: "Large", dimensions: "Ø 45 mm", price: 13500, compare_at_price: null },
    ],
    badge: null,
    featured: false,
    in_stock: true,
  },

  // ── Fashion & Accessories ──────────────────────────────────────────────
  {
    id: "p25",
    slug: "batik-silk-scarf",
    name: "Hand-Painted Batik Silk Scarf",
    category_slug: "fashion",
    short_description: "Wax-resist batik on mulberry silk, painted by one artisan.",
    description:
      "Traditional wax-resist batik on 16-momme mulberry silk, drawn freehand in a botanical pattern of ivory, dusty blue and gold. Each scarf takes three days and passes through one pair of hands — small variations in the line are the signature, not the flaw.",
    material: "16-momme mulberry silk, hand-drawn batik",
    details: [
      "90 × 90 cm, hand-rolled edges",
      "Wax-resist batik drawn freehand",
      "Colour-fast natural and reactive dyes",
      "Each piece signed by its artisan",
    ],
    care: ["Dry clean only", "Store rolled, not folded, to avoid creases"],
    colors: ["Ivory", "Dusty Blue", "Gold"],
    images: shots("batik-silk-scarf"),
    sizes: [
      { name: "90 × 90 cm", dimensions: "Square", price: 16500, compare_at_price: null },
      { name: "180 × 55 cm", dimensions: "Long stole", price: 21500, compare_at_price: null },
    ],
    badge: "New",
    featured: true,
    in_stock: true,
  },
  {
    id: "p26",
    slug: "washed-linen-shirt-dress",
    name: "Washed Linen Shirt Dress",
    category_slug: "fashion",
    short_description: "European flax, garment-washed, with real horn buttons.",
    description:
      "Cut from heavyweight European flax and garment-washed until it drapes rather than stands. A relaxed shirt silhouette with a removable belt, deep side pockets and genuine horn buttons — it goes to the office, then straight to dinner, and never once looks creased in the wrong way.",
    material: "100% European flax linen, garment washed",
    details: [
      "Relaxed shirt silhouette with a removable belt",
      "Deep side seam pockets",
      "Genuine horn buttons",
      "Pre-washed — no shrinkage surprises",
    ],
    care: ["Machine wash cool on gentle", "Line dry", "Warm iron while slightly damp"],
    colors: ["Oat", "Ivory"],
    images: shots("washed-linen-shirt-dress"),
    sizes: [
      { name: "XS", dimensions: "UK 6–8", price: 22500, compare_at_price: null },
      { name: "S", dimensions: "UK 8–10", price: 22500, compare_at_price: null },
      { name: "M", dimensions: "UK 10–12", price: 22500, compare_at_price: null },
      { name: "L", dimensions: "UK 14–16", price: 23500, compare_at_price: null },
    ],
    badge: null,
    featured: true,
    in_stock: true,
  },
  {
    id: "p27",
    slug: "palmyrah-woven-tote",
    name: "Palmyrah Woven Tote",
    category_slug: "fashion",
    short_description: "Hand-woven palmyrah leaf with vegetable-tanned handles.",
    description:
      "Woven from palmyrah palm leaf by artisans in the island's north, using a craft that has been passed down through generations of the same families. Fitted with vegetable-tanned leather handles and a lined interior, so it works as a market basket or a weekend bag.",
    material: "Hand-woven palmyrah leaf, vegetable-tanned leather handles",
    details: [
      "Hand-woven by artisans in northern Sri Lanka",
      "Vegetable-tanned leather handles that patina",
      "Cotton-lined interior with an inner pocket",
      "Holds up to 8 kg comfortably",
    ],
    care: ["Wipe with a dry cloth", "Keep dry — do not soak the weave"],
    colors: ["Natural", "Tan"],
    images: shots("palmyrah-woven-tote"),
    sizes: [
      { name: "Medium", dimensions: "34 × 30 × 14 cm", price: 12500, compare_at_price: null },
      { name: "Large", dimensions: "42 × 36 × 16 cm", price: 15500, compare_at_price: null },
    ],
    badge: null,
    featured: false,
    in_stock: true,
  },
  {
    id: "p28",
    slug: "leather-crossbody-bag",
    name: "Vegetable-Tanned Crossbody Bag",
    category_slug: "fashion",
    short_description: "Full-grain leather that darkens beautifully with use.",
    description:
      "Full-grain leather, vegetable-tanned over six weeks with tree bark rather than chemicals, so it arrives pale and honey-coloured and darkens into something entirely your own. Solid brass hardware, an adjustable strap, and enough room for a phone, a wallet and not much else — which is the point.",
    material: "Full-grain vegetable-tanned leather, solid brass hardware",
    details: [
      "Full-grain leather, six-week bark tanning",
      "Solid brass hardware, not plated",
      "Adjustable strap: crossbody or shoulder",
      "Develops a unique patina with wear",
    ],
    care: ["Condition twice a year with a leather balm", "Keep out of prolonged direct sun"],
    colors: ["Tan"],
    images: shots("leather-crossbody-bag"),
    sizes: [{ name: "One size", dimensions: "22 × 16 × 7 cm", price: 26500, compare_at_price: null }],
    badge: null,
    featured: false,
    in_stock: true,
  },
  {
    id: "p29",
    slug: "resort-linen-kaftan",
    name: "Resort Linen Kaftan",
    category_slug: "fashion",
    short_description: "Featherweight linen with hand-embroidered gold thread.",
    description:
      "Featherweight European linen, cut wide and easy, with gold thread hand-embroidered around the neckline by a single embroiderer. It goes over a swimsuit at noon and over trousers at dinner, and it packs down to almost nothing.",
    material: "Lightweight European flax linen, hand-embroidered gold thread",
    details: [
      "Hand-embroidered neckline — 4 hours per piece",
      "Featherweight 120 gsm linen",
      "Relaxed one-size cut with side splits",
      "Packs flat; shakes out crease-free",
    ],
    care: ["Machine wash cool on gentle", "Line dry in shade", "Cool iron the embroidery from the reverse"],
    colors: ["Ivory", "Gold"],
    images: shots("resort-linen-kaftan"),
    sizes: [{ name: "One size", dimensions: "Fits UK 8–16", price: 19500, compare_at_price: 24500 }],
    badge: "Save 20%",
    featured: true,
    in_stock: true,
  },
  {
    id: "p30",
    slug: "raffia-sun-hat",
    name: "Raffia Sun Hat",
    category_slug: "fashion",
    short_description: "Wide-brim raffia with a grosgrain band — packs flat.",
    description:
      "Hand-woven Madagascan raffia with a 10 cm brim and an ivory grosgrain band. Stiff enough to hold its shape against a sea breeze, soft enough to roll into a suitcase and shake back out at the other end.",
    material: "Hand-woven Madagascan raffia, grosgrain ribbon band",
    details: [
      "10 cm brim — genuine shade, not decoration",
      "Internal drawstring for a precise fit",
      "Packs flat and recovers its shape",
      "UPF 50+ weave density",
    ],
    care: ["Store flat or on a hook", "Reshape the brim by hand when damp"],
    colors: ["Natural", "Ivory"],
    images: shots("raffia-sun-hat"),
    sizes: [{ name: "One size", dimensions: "56–58 cm adjustable", price: 8900, compare_at_price: null }],
    badge: null,
    featured: false,
    in_stock: true,
  },

  // ── Fine Bedlinen & Sleep Luxury ───────────────────────────────────────
  {
    id: "p31",
    slug: "cloud-percale-sheet-set",
    name: "Cloud Percale Sheet Set",
    category_slug: "bedlinen",
    short_description: "Crisp, cool 400-thread percale in cloud ivory.",
    description:
      "Woven from long-staple cotton in a tight percale weave, the Cloud set sleeps crisp and cool the whole year round — the hotel-sheet feeling, without the starch. Flat sheet, fitted sheet and two pillowcases, all double-stitched at the hem.",
    material: "100% long-staple cotton, 400 thread count percale",
    details: [
      "Flat sheet, fitted sheet and two pillowcases",
      "Deep 40 cm fitted-sheet pocket",
      "Softens with every wash, never pills",
      "OEKO-TEX certified — no harsh finishes",
    ],
    care: ["Machine wash cold on gentle", "Tumble dry low", "Warm iron if you like the crispness"],
    colors: ["Ivory", "Oat"],
    images: shots("cloud-percale-sheet-set"),
    sizes: [
      { name: "Single", dimensions: "150 × 220 cm", price: 12500, compare_at_price: null },
      { name: "Double", dimensions: "200 × 220 cm", price: 14500, compare_at_price: null },
      { name: "Queen", dimensions: "230 × 250 cm", price: 16500, compare_at_price: null },
      { name: "King", dimensions: "260 × 270 cm", price: 18500, compare_at_price: null },
    ],
    badge: "Bestseller",
    featured: true,
    in_stock: true,
  },
  {
    id: "p32",
    slug: "stonewashed-linen-sheet-set",
    name: "Stonewashed Linen Sheet Set",
    category_slug: "bedlinen",
    short_description: "Garment-washed European flax with a lived-in softness.",
    description:
      "Our signature linen is stonewashed before it reaches you, so it arrives soft and tumbled instead of asking for a year of patience. Naturally temperature-regulating — cool through a Colombo April, warm enough in an over-conditioned room.",
    material: "100% European flax linen, stonewashed",
    details: [
      "Pre-washed — no shrinkage surprises",
      "Naturally breathable and moisture-wicking",
      "Yarn-dyed for colour that lasts",
      "Gets softer every single wash",
    ],
    care: ["Machine wash warm", "Line dry or tumble dry low", "No ironing needed"],
    colors: ["Oat", "Dusty Blue"],
    images: shots("stonewashed-linen-sheet-set"),
    sizes: [
      { name: "Double", dimensions: "200 × 220 cm", price: 19500, compare_at_price: null },
      { name: "Queen", dimensions: "230 × 250 cm", price: 22500, compare_at_price: null },
      { name: "King", dimensions: "260 × 270 cm", price: 25500, compare_at_price: null },
    ],
    badge: null,
    featured: true,
    in_stock: true,
  },
  {
    id: "p33",
    slug: "enivrant-signature-bedding-set",
    name: "Enivrant Signature Bedding Set",
    category_slug: "bedlinen",
    short_description: "The complete bed — save 20% against unit prices.",
    description:
      "Everything the bed needs in one box: flat sheet, fitted sheet, duvet cover and four pillowcases in our signature percale, curated to match and priced 20% below buying each piece alone. It arrives in a cotton keeper bag, which is where it lives between seasons.",
    material: "100% long-staple cotton, 400 thread count percale",
    details: [
      "7 pieces: flat, fitted, duvet cover, four pillowcases",
      "Save 20% against unit prices",
      "Presented in a reusable cotton keeper bag",
      "OEKO-TEX certified throughout",
    ],
    care: ["Machine wash cold", "Tumble dry low"],
    colors: ["Ivory", "Champagne"],
    images: shots("enivrant-signature-bedding-set"),
    sizes: [
      { name: "Double", dimensions: "7-piece set", price: 36500, compare_at_price: 45500 },
      { name: "Queen", dimensions: "7-piece set", price: 39500, compare_at_price: 49500 },
      { name: "King", dimensions: "7-piece set", price: 42500, compare_at_price: 53000 },
    ],
    badge: "Save 20%",
    featured: true,
    in_stock: true,
  },
  {
    id: "p34",
    slug: "mulberry-silk-pillowcase-pair",
    name: "Mulberry Silk Pillowcase Pair",
    category_slug: "bedlinen",
    short_description: "22-momme grade 6A silk — kinder to hair and skin.",
    description:
      "22-momme grade 6A mulberry silk, the weight hotels use and the grade most brands quietly skip. Silk does not wick moisture out of skin and hair the way cotton does, and it does not crease a face overnight. Hidden zip closure, so nothing shows.",
    material: "22-momme grade 6A mulberry silk",
    details: [
      "Pair of pillowcases, hidden zip closure",
      "22-momme weight, grade 6A long-fibre silk",
      "Naturally hypoallergenic and temperature-regulating",
      "OEKO-TEX certified dyes",
    ],
    care: ["Machine wash cold in a mesh bag on delicate", "Dry flat away from sunlight", "Cool iron on the reverse"],
    colors: ["Champagne", "Ivory"],
    images: shots("mulberry-silk-pillowcase-pair"),
    sizes: [
      { name: "Standard", dimensions: "50 × 75 cm (×2)", price: 18500, compare_at_price: null },
      { name: "King", dimensions: "50 × 90 cm (×2)", price: 21500, compare_at_price: null },
    ],
    badge: null,
    featured: true,
    in_stock: true,
  },
  {
    id: "p35",
    slug: "goose-down-duvet",
    name: "European Goose Down Duvet",
    category_slug: "bedlinen",
    short_description: "800-fill-power down in a baffle-box cotton shell.",
    description:
      "800-fill-power European goose down in a baffle-box construction, so the down stays where it should instead of migrating to the corners by February. Wrapped in a 300-thread cotton cambric shell that keeps every feather exactly where you put it.",
    material: "800 fill power European goose down, 300TC cotton cambric shell",
    details: [
      "Baffle-box construction — no cold spots",
      "800 fill power: maximum warmth, minimum weight",
      "Down-proof 300-thread cotton cambric shell",
      "Responsible Down Standard certified",
    ],
    care: ["Air monthly; wash yearly on a down cycle", "Tumble dry low with dryer balls"],
    colors: ["Ivory"],
    images: shots("goose-down-duvet"),
    sizes: [
      { name: "Double — all season", dimensions: "200 × 220 cm", price: 44500, compare_at_price: null },
      { name: "Queen — all season", dimensions: "230 × 220 cm", price: 49500, compare_at_price: null },
      { name: "King — all season", dimensions: "260 × 240 cm", price: 56500, compare_at_price: null },
    ],
    badge: null,
    featured: false,
    in_stock: true,
  },
  {
    id: "p36",
    slug: "waffle-weave-blanket",
    name: "Waffle Weave Blanket",
    category_slug: "bedlinen",
    short_description: "An airy honeycomb weave that layers beautifully.",
    description:
      "The honeycomb structure traps air for warmth without any weight, which makes it the most useful blanket in the house — under a duvet in the cold months, alone in the warm ones, and folded across the end of the bed for the rest of the year.",
    material: "100% combed cotton waffle weave",
    details: [
      "Lightweight, breathable warmth",
      "Pre-washed for immediate softness",
      "Clean selvedge edge finish",
      "Layers under any duvet without bulk",
    ],
    care: ["Machine wash cold", "Tumble dry low"],
    colors: ["Oat", "Ivory"],
    images: shots("waffle-weave-blanket"),
    sizes: [
      { name: "Double", dimensions: "200 × 220 cm", price: 13500, compare_at_price: null },
      { name: "King", dimensions: "240 × 260 cm", price: 15500, compare_at_price: null },
    ],
    badge: null,
    featured: false,
    in_stock: true,
  },
];
