import type { Category, Product } from "./types";

const u = (id: string, w = 1600) =>
  `https://images.unsplash.com/photo-${id}?w=${w}&q=80&auto=format&fit=crop`;

export const seedCategories: Category[] = [
  {
    id: "c1",
    slug: "kitchen",
    name: "Kitchen",
    description: "Hand-thrown stoneware, teak boards and linen textiles for the heart of the home.",
    image: "/images/categories/kitchen.png",
    sort_order: 1,
  },
  {
    id: "c2",
    slug: "bedroom",
    name: "Bedroom",
    description: "Bedding, bedside lighting and calm details for rooms made to rest in.",
    image: "/images/categories/bedroom.png",
    sort_order: 2,
  },
  {
    id: "c3",
    slug: "lounge",
    name: "Lounge",
    description: "Handloom throws, rattan lighting, vases and candles for rooms you live in.",
    image: "/images/categories/lounge.png",
    sort_order: 3,
  },
  {
    id: "c4",
    slug: "bathroom",
    name: "Bathroom",
    description: "Organic towels, teak caddies and waffle robes — an everyday spa at home.",
    image: "/images/categories/bathroom.png",
    sort_order: 4,
  },
  {
    id: "c5",
    slug: "garden",
    name: "Garden",
    description: "Terracotta planters, handloom cushions and weatherproof layers for life outdoors.",
    image: "/images/categories/garden.png",
    sort_order: 5,
  },
  {
    id: "c6",
    slug: "garage",
    name: "Garage",
    description: "Sturdy storage, canvas organisers and workshop-grade utility, made beautiful.",
    image: "/images/categories/garage.png",
    sort_order: 6,
  },
];

export const seedProducts: Product[] = [
  // ── Kitchen ────────────────────────────────────────────────────────────
  {
    id: "p1",
    slug: "glazed-stoneware-dinner-set",
    name: "Glazed Stoneware Dinner Set",
    category_slug: "kitchen",
    short_description: "Hand-thrown stoneware in a speckled, small-batch glaze.",
    description:
      "Thrown on the wheel and glazed in small batches, no two pieces of this dinner set are exactly alike — and that's the point. Generous plates, deep bowls and mugs that keep tea warm, all fired to survive daily use and the dishwasher.",
    material: "Hand-thrown stoneware, lead-free speckled glaze",
    details: [
      "12-piece set: 4 dinner plates, 4 bowls, 4 mugs",
      "Each piece thrown and glazed by hand",
      "Dishwasher and microwave safe",
      "Chip-resistant high-fire stoneware",
    ],
    care: ["Dishwasher safe on a normal cycle", "Avoid thermal shock — no oven-to-fridge"],
    colors: ["Speckled Cream", "Sage", "Terracotta"],
    images: [u("1610701596007-11502861dcfa"), u("1603199506016-b9a594b593c0")],
    sizes: [
      { name: "12-piece set", dimensions: "4 place settings", price: 24500, compare_at_price: null },
      { name: "18-piece set", dimensions: "6 place settings", price: 34500, compare_at_price: null },
    ],
    badge: "New",
    featured: true,
    in_stock: true,
  },
  {
    id: "p2",
    slug: "teak-serving-boards",
    name: "Teak Serving Board Duo",
    category_slug: "kitchen",
    short_description: "Reclaimed solid teak, shaped and oiled by hand.",
    description:
      "Cut from reclaimed Sri Lankan teak and finished with food-safe oil, these boards go from chopping to serving without a costume change. The grain deepens beautifully with use — wipe, oil occasionally, and they'll outlast the kitchen.",
    material: "Solid reclaimed teak, food-safe oil finish",
    details: [
      "Sold as a pair — one for prep, one for the table",
      "Reclaimed timber, no two boards alike",
      "Integrated handle with leather hanging loop",
      "Naturally antibacterial dense grain",
    ],
    care: ["Hand wash and dry upright", "Re-oil monthly with food-safe mineral oil", "Never soak or dishwash"],
    colors: ["Natural Teak"],
    images: [u("1605522561233-768ad7a8fabf"), u("1541529086526-db283c563270")],
    sizes: [
      { name: "Duo", dimensions: "20 × 35 cm + 25 × 45 cm", price: 9800, compare_at_price: null },
    ],
    badge: null,
    featured: false,
    in_stock: true,
  },
  {
    id: "p3",
    slug: "washed-linen-apron",
    name: "Washed Linen Apron",
    category_slug: "kitchen",
    short_description: "Artisanal cross-back linen apron with deep front pockets.",
    description:
      "Sewn from heavy European flax linen, this cross-back apron distributes weight evenly across your shoulders, not your neck. Features double-stitched utility pockets and a relaxed, lived-in drape that only gets better with wash and wear.",
    material: "100% European flax linen, washed finish",
    details: [
      "Comfortable cross-back design (no neck ties)",
      "Two deep front utility pockets",
      "Reinforced stitching at stress points",
      "One size fits most",
    ],
    care: ["Machine wash warm", "Tumble dry low", "No ironing needed"],
    colors: ["Oatmeal", "Charcoal", "Sage"],
    images: [u("1556910103001-cf37a8c24207"), u("1590794056226-79ef3a8147e1")],
    sizes: [{ name: "One Size", dimensions: "85 × 90 cm", price: 8500, compare_at_price: null }],
    badge: null,
    featured: false,
    in_stock: true,
  },
  {
    id: "p4",
    slug: "waffle-kitchen-towels",
    name: "Waffle Kitchen Towels (Set of 3)",
    category_slug: "kitchen",
    short_description: "Thirsty honeycomb kitchen towels in earthy neutrals.",
    description:
      "A pack of three highly absorbent, waffle-woven kitchen towels. Woven from a durable cotton-linen blend that dries quickly and leaves no lint on glassware. Finished with a woven hanging loop.",
    material: "80% long-staple cotton, 20% European linen",
    details: [
      "Set of three matching towels",
      "Quick-drying honeycomb waffle weave",
      "Lint-free drying for glassware",
      "Integrated hanging loop",
    ],
    care: ["Machine wash warm", "Tumble dry medium"],
    colors: ["Natural Mix", "Sage Mix"],
    images: [u("1607344645866-009c320c5ab8"), u("1607344646505-0e7b41cfba45")],
    sizes: [{ name: "Standard Pack", dimensions: "45 × 65 cm (x3)", price: 5900, compare_at_price: null }],
    badge: null,
    featured: false,
    in_stock: true,
  },

  // ── Bedroom ────────────────────────────────────────────────────────────
  {
    id: "p5",
    slug: "cloud-percale-sheet-set",
    name: "Cloud Percale Sheet Set",
    category_slug: "bedroom",
    short_description: "Crisp, cool 400-thread percale in cloud white.",
    description:
      "Woven from long-staple cotton in a tight percale weave, the Cloud set sleeps crisp and cool all year round. Each set includes one flat sheet, one fitted sheet and two pillowcases, finished with a double-stitched hem.",
    material: "100% long-staple cotton, 400 thread count percale",
    details: [
      "Includes flat sheet, fitted sheet and two pillowcases",
      "Deep 40 cm fitted-sheet pocket",
      "Gets softer with every wash",
      "OEKO-TEX certified, free of harsh chemicals",
    ],
    care: ["Machine wash cold on gentle", "Tumble dry low", "Warm iron if desired"],
    colors: ["Cloud White", "Oat", "Sage"],
    images: [u("1631049307264-da0ec9d70304"), u("1631049035182-249067d7618e")],
    sizes: [
      { name: "Single", dimensions: "150 × 220 cm", price: 12500, compare_at_price: null },
      { name: "Double", dimensions: "200 × 220 cm", price: 14500, compare_at_price: null },
      { name: "Queen", dimensions: "230 × 250 cm", price: 16500, compare_at_price: null },
      { name: "King", dimensions: "260 × 270 cm", price: 18500, compare_at_price: null },
    ],
    badge: "Bestseller",
    featured: true,
    in_stock: true,
  },
  {
    id: "p6",
    slug: "stonewashed-linen-sheet-set",
    name: "Stonewashed Linen Sheet Set",
    category_slug: "bedroom",
    short_description: "Garment-washed European flax with a lived-in softness.",
    description:
      "Our signature linen is stonewashed for a soft, tumbled texture from the very first night. Naturally temperature-regulating, it keeps you cool in the heat and cosy in the cold.",
    material: "100% European flax linen, stonewashed",
    details: [
      "Pre-washed for zero shrinkage surprises",
      "Naturally breathable and moisture-wicking",
      "Yarn-dyed for rich, lasting colour",
    ],
    care: ["Machine wash warm", "Line dry or tumble dry low", "No ironing needed"],
    colors: ["Natural", "Terracotta", "Charcoal"],
    images: [u("1595526114035-0d45ed16cfbf"), u("1522771739844-6a9f6d5f14af")],
    sizes: [
      { name: "Double", dimensions: "200 × 220 cm", price: 19500, compare_at_price: null },
      { name: "Queen", dimensions: "230 × 250 cm", price: 22500, compare_at_price: null },
      { name: "King", dimensions: "260 × 270 cm", price: 25500, compare_at_price: null },
    ],
    badge: null,
    featured: false,
    in_stock: true,
  },
  {
    id: "p7",
    slug: "terracotta-linen-duvet-set",
    name: "Terracotta Linen Duvet Set",
    category_slug: "bedroom",
    short_description: "Sun-baked terracotta linen, hand-finished with ties.",
    description:
      "The set from our campaign imagery. Deep terracotta linen, stonewashed to a soft slub texture and finished with hand-tied corner closures that keep your duvet exactly where it should be.",
    material: "100% European flax linen, stonewashed",
    details: [
      "Includes duvet cover and two pillowcases",
      "Hand-tied closures, interior corner ties",
      "Dyed in small batches for depth of colour",
    ],
    care: ["Machine wash warm", "Line dry", "No ironing needed"],
    colors: ["Terracotta", "Ochre"],
    images: [u("1616594039964-ae9021a400a0"), u("1586023492125-27b2c045efd7")],
    sizes: [
      { name: "Double", dimensions: "200 × 200 cm", price: 24500, compare_at_price: null },
      { name: "Queen", dimensions: "225 × 220 cm", price: 27500, compare_at_price: null },
      { name: "King", dimensions: "245 × 240 cm", price: 29500, compare_at_price: null },
    ],
    badge: "Bestseller",
    featured: true,
    in_stock: true,
  },
  {
    id: "p8",
    slug: "ivory-homez-signature-bedding-set",
    name: "Ivory Homez Signature Bedding Set",
    category_slug: "bedroom",
    short_description: "The complete Ivory Homez bed — save 20% over unit prices.",
    description:
      "Everything your bed needs in one box: flat sheet, fitted sheet, duvet cover and four pillowcases in our signature percale. Curated to match, priced to save — 20% less than buying each piece alone.",
    material: "100% long-staple cotton, 400 thread count percale",
    details: [
      "7-piece set: flat, fitted, duvet cover, four pillowcases",
      "Save 20% versus unit prices",
      "Gift-ready cotton keeper bag",
    ],
    care: ["Machine wash cold", "Tumble dry low"],
    colors: ["Cloud White", "Oat", "Terracotta"],
    images: [u("1560185893-a55cbc8c57e8"), u("1586023492125-27b2c045efd7")],
    sizes: [
      { name: "Double", dimensions: "7-piece set", price: 36500, compare_at_price: 45500 },
      { name: "Queen", dimensions: "7-piece set", price: 39500, compare_at_price: 49500 },
      { name: "King", dimensions: "7-piece set", price: 42500, compare_at_price: 53000 },
    ],
    badge: "Save 20%",
    featured: true,
    in_stock: true,
  },
  {
    id: "p9",
    slug: "teak-bedside-table",
    name: "Teak Bedside Table",
    category_slug: "bedroom",
    short_description: "Solid teak side table, cut and oiled by hand.",
    description:
      "A quiet piece of furniture that earns its place: solid Sri Lankan teak, hand-cut joinery and a lower shelf for the book you're actually reading. Oiled, never lacquered, so the grain keeps breathing.",
    material: "Solid teak, hand-oiled finish",
    details: [
      "Solid timber throughout — no veneers",
      "Traditional hand-cut joinery, no visible fixings",
      "Lower shelf for books and baskets",
      "Grain and tone vary board to board",
    ],
    care: ["Dust with a dry cloth", "Re-oil yearly to refresh the finish", "Keep clear of direct radiator heat"],
    colors: ["Natural Teak"],
    images: [u("1611486212557-88be5ff6f941"), u("1499933374294-4584851497cc")],
    sizes: [{ name: "One Size", dimensions: "45 × 35 × 55 cm", price: 16500, compare_at_price: null }],
    badge: null,
    featured: false,
    in_stock: true,
  },

  // ── Lounge ─────────────────────────────────────────────────────────────
  {
    id: "p10",
    slug: "handloom-cotton-throw",
    name: "Handloom Cotton Throw",
    category_slug: "lounge",
    short_description: "Handwoven on wooden looms with knotted fringe.",
    description:
      "Each throw is handwoven on traditional wooden looms, then finished with a hand-knotted fringe. Perfect at the foot of the bed or over the shoulder on cool evenings.",
    material: "100% handloom cotton",
    details: ["Handwoven, small-batch", "Hand-knotted fringe", "Ethically made in Sri Lanka"],
    care: ["Gentle machine wash cold", "Line dry"],
    colors: ["Natural Stripe", "Clay Stripe"],
    images: [u("1519710164239-da123dc03ef4"), u("1560185127-6ed189bf02f4")],
    sizes: [{ name: "One Size", dimensions: "130 × 180 cm", price: 9800, compare_at_price: null }],
    badge: null,
    featured: true,
    in_stock: true,
  },
  {
    id: "p11",
    slug: "waffle-weave-blanket",
    name: "Waffle Weave Blanket",
    category_slug: "lounge",
    short_description: "Airy honeycomb weave that layers beautifully.",
    description:
      "The honeycomb structure traps air for warmth without weight. Layer it under a duvet in the cold months or use it alone in the warm ones.",
    material: "100% combed cotton waffle weave",
    details: ["Lightweight, breathable warmth", "Pre-washed for softness", "Selvedge edge finish"],
    care: ["Machine wash cold", "Tumble dry low"],
    colors: ["Oat", "Stone", "Sage"],
    images: [u("1567016432779-094069958ea5"), u("1505691938895-1758d7feb511")],
    sizes: [
      { name: "Double", dimensions: "200 × 220 cm", price: 13500, compare_at_price: null },
      { name: "King", dimensions: "240 × 260 cm", price: 15500, compare_at_price: null },
    ],
    badge: null,
    featured: false,
    in_stock: true,
  },
  {
    id: "p12",
    slug: "hand-thrown-ceramic-vase",
    name: "Hand-Thrown Ceramic Vase",
    category_slug: "lounge",
    short_description: "Wheel-thrown stoneware with a quiet matte glaze.",
    description:
      "Thrown on the wheel in our workshop, each vase carries the maker's finger lines under a quiet matte glaze. Weighted to hold a full branch without tipping — or to stand beautifully empty.",
    material: "Wheel-thrown stoneware, matte glaze",
    details: [
      "Each piece is one of one — glaze and lines vary",
      "Watertight, sealed interior",
      "Weighted base for tall stems",
    ],
    care: ["Rinse and hand dry", "Avoid abrasive scrubbing on the glaze"],
    colors: ["Cream", "Clay", "Charcoal"],
    images: [u("1581783342308-f792dbdd27c5"), u("1578500494198-246f612d3b3d")],
    sizes: [
      { name: "Small", dimensions: "H 18 cm", price: 4900, compare_at_price: null },
      { name: "Medium", dimensions: "H 26 cm", price: 6900, compare_at_price: null },
      { name: "Large", dimensions: "H 34 cm", price: 8900, compare_at_price: null },
    ],
    badge: null,
    featured: false,
    in_stock: true,
  },
  {
    id: "p13",
    slug: "rattan-pendant-light",
    name: "Rattan Pendant Light",
    category_slug: "lounge",
    short_description: "Hand-woven pendant that turns light into texture.",
    description:
      "Woven from natural rattan over a brass fitting, this pendant throws a warm lattice of light and shadow across the room. Hang it low over a dining table or in a reading corner — it makes the evening.",
    material: "Hand-woven natural rattan, brass fitting",
    details: [
      "Casts a warm, patterned lattice of light",
      "1.5 m adjustable cord, ceiling rose included",
      "Fits a standard E27 bulb (not included)",
      "Each shade woven by hand — patterns vary slightly",
    ],
    care: ["Dust with a dry cloth or soft brush", "Indoor use only"],
    colors: ["Natural", "Honey"],
    images: [u("1615529182904-14819c35db37"), u("1519643381401-22c77e60520e")],
    sizes: [
      { name: "Medium", dimensions: "Ø 40 cm", price: 14500, compare_at_price: null },
      { name: "Large", dimensions: "Ø 55 cm", price: 18500, compare_at_price: null },
    ],
    badge: "New",
    featured: true,
    in_stock: true,
  },
  {
    id: "p14",
    slug: "hand-poured-candle-trio",
    name: "Hand-Poured Candle Trio",
    category_slug: "lounge",
    short_description: "Soy candles in reusable stoneware vessels.",
    description:
      "Three slow-burning soy candles poured by hand into our own stoneware cups. Scents drawn from the island — cinnamon and teak, Ceylon tea, sea salt — with vessels you'll refill or repurpose long after the wax is gone.",
    material: "Natural soy wax, cotton wicks, stoneware vessels",
    details: [
      "Set of three: Cinnamon & Teak, Ceylon Tea, Sea Salt",
      "About 40 hours of burn time each",
      "Reusable hand-thrown stoneware cups",
      "Phthalate-free fragrance oils",
    ],
    care: ["Trim wick to 5 mm before each burn", "First burn: let the full surface melt"],
    colors: ["Cream", "Sand"],
    images: [u("1603006905003-be475563bc59"), u("1602523961358-f9f03dd557db")],
    sizes: [{ name: "Set of 3", dimensions: "3 × 180 g", price: 7500, compare_at_price: null }],
    badge: null,
    featured: false,
    in_stock: true,
  },
  {
    id: "p15",
    slug: "oak-wall-shelf-set",
    name: "Oak Wall Shelf Set",
    category_slug: "lounge",
    short_description: "Solid oak floating shelves with concealed brackets.",
    description:
      "Two lengths of solid oak, planed and waxed by hand, floating on concealed steel brackets. Strong enough for a shelf of books, handsome enough for the three objects you actually want to look at.",
    material: "Solid oak, concealed steel brackets",
    details: [
      "Set of 2: 60 cm + 80 cm lengths",
      "Concealed steel brackets, fixings included",
      "Holds up to 15 kg per shelf when wall-anchored",
      "Hand-waxed finish shows the natural grain",
    ],
    care: ["Dust with a dry cloth", "Re-wax yearly for a fresh finish"],
    colors: ["Natural Oak"],
    images: [u("1594620302200-9a762244a156"), u("1595428774223-ef52624120d2")],
    sizes: [{ name: "Set of 2", dimensions: "60 cm + 80 cm × D 20 cm", price: 12500, compare_at_price: null }],
    badge: null,
    featured: false,
    in_stock: true,
  },

  // ── Bathroom ───────────────────────────────────────────────────────────
  {
    id: "p16",
    slug: "organic-bath-towels",
    name: "Plush Organic Cotton Bath Towels",
    category_slug: "bathroom",
    short_description: "Extra-plush combed cotton towels woven to 700 GSM.",
    description:
      "Wrap yourself in pure luxury. Our organic cotton bath towels are combed for softness and woven to a substantial 700 GSM for ultimate absorbency and warmth. Finished with a clean, classic border.",
    material: "100% organic long-staple cotton, 700 GSM",
    details: [
      "Extra-thick and highly absorbent",
      "GOTS certified organic cotton",
      "Fade-resistant, low-lint weave",
      "Sold individually or as a pair",
    ],
    care: ["Machine wash hot with like colors", "Tumble dry high", "Do not use fabric softener"],
    colors: ["Cloud White", "Oat", "Stone"],
    images: [u("1616627561954-252214724e5b"), u("1540555700478-4be289fbecef")],
    sizes: [
      { name: "Bath Towel", dimensions: "70 × 140 cm", price: 9500, compare_at_price: null },
      { name: "Bath Sheet", dimensions: "100 × 150 cm", price: 12500, compare_at_price: null },
    ],
    badge: "Bestseller",
    featured: true,
    in_stock: true,
  },
  {
    id: "p17",
    slug: "waffle-bathrobe",
    name: "Waffle Cotton Bathrobe",
    category_slug: "bathroom",
    short_description: "Lightweight, spa-style waffle bathrobe with waist tie.",
    description:
      "Inspired by the finest boutique hotels, our waffle bathrobe offers a lightweight, breathable cover-up for post-bath relaxation. The honeycomb weave gently exfoliates and dries quickly. Featuring two deep hip pockets and an adjustable tie belt.",
    material: "100% organic cotton, 350 GSM waffle weave",
    details: [
      "Unisex classic kimono silhouette",
      "Adjustable double belt loops for custom fit",
      "Two deep pockets",
      "Pre-shrunk for lasting fit",
    ],
    care: ["Machine wash warm", "Tumble dry low"],
    colors: ["Oat", "Cloud White"],
    images: [u("1556909114-f6e7ad7d3136"), u("1556909181-ed82035af743")],
    sizes: [
      { name: "S/M", dimensions: "Chest 120cm, Length 115cm", price: 18500, compare_at_price: null },
      { name: "L/XL", dimensions: "Chest 135cm, Length 122cm", price: 18500, compare_at_price: null },
    ],
    badge: null,
    featured: false,
    in_stock: true,
  },
  {
    id: "p18",
    slug: "teak-bath-caddy",
    name: "Teak Bath Caddy",
    category_slug: "bathroom",
    short_description: "Extendable solid teak tray for slow evenings in the tub.",
    description:
      "A bath, a book and somewhere to rest the tea. Cut from naturally water-resistant teak and finished with oil, this extendable caddy spans most tubs and holds the evening's essentials — reader, glass, candle and all.",
    material: "Solid teak, water-resistant natural oil finish",
    details: [
      "Extends from 70 to 86 cm to fit most tubs",
      "Recessed glass holder and book rest",
      "Naturally water- and warp-resistant teak",
      "Rubber grips keep it steady on acrylic tubs",
    ],
    care: ["Wipe dry after use", "Re-oil every few months", "Do not leave submerged"],
    colors: ["Natural Teak"],
    images: [u("1552321554-5fefe8c9ef14"), u("1620626011761-996317b8d101")],
    sizes: [{ name: "One Size", dimensions: "70–86 × 23 cm", price: 9800, compare_at_price: null }],
    badge: "New",
    featured: true,
    in_stock: true,
  },
  {
    id: "p19",
    slug: "waffle-bath-mat",
    name: "Waffle Bath Mat",
    category_slug: "bathroom",
    short_description: "Dense 900 GSM waffle cotton underfoot.",
    description:
      "Woven thick at 900 GSM, this waffle mat drinks up water and dries fast, with a honeycomb texture that feels like a gentle foot massage first thing in the morning.",
    material: "100% organic cotton, 900 GSM waffle weave",
    details: [
      "Ultra-absorbent honeycomb weave",
      "Quick-drying, low-lint construction",
      "Finished with a tailored flat border",
    ],
    care: ["Machine wash warm", "Tumble dry medium", "No fabric softener"],
    colors: ["Oat", "Cloud White", "Stone"],
    images: [u("1540555700478-4be289fbecef"), u("1620626011761-996317b8d101")],
    sizes: [{ name: "One Size", dimensions: "50 × 80 cm", price: 4900, compare_at_price: null }],
    badge: null,
    featured: false,
    in_stock: true,
  },

  // ── Garden ─────────────────────────────────────────────────────────────
  {
    id: "p20",
    slug: "handloom-seat-cushions",
    name: "Handloom Cotton Seat Cushions",
    category_slug: "garden",
    short_description: "Handwoven box cushions with convenient tie-backs.",
    description:
      "Bring comfort and artisan craftsmanship to your garden dining set. These thick box cushions are handwoven on wooden looms from heavy-weight cotton, filled with supportive recycled fibers and finished with secure ties.",
    material: "100% handloom cotton shell, recycled fiber fill",
    details: [
      "Heavy-duty handwoven canvas shell",
      "Tufted details for shape retention",
      "Two robust tie-backs for secure fastening",
      "Ethically crafted by artisans",
    ],
    care: ["Spot clean only", "Store indoors when not in use", "Air dry thoroughly"],
    colors: ["Natural Stripe", "Sage Stripe", "Charcoal Stripe"],
    images: [u("1600585154340-be6161a56a0c"), u("1600585154526-7ee658dfa8e4")],
    sizes: [{ name: "One Size", dimensions: "40 × 40 × 8 cm", price: 6800, compare_at_price: null }],
    badge: null,
    featured: false,
    in_stock: true,
  },
  {
    id: "p21",
    slug: "patio-waffle-throw",
    name: "Textured Patio Throw",
    category_slug: "garden",
    short_description: "Durable, wind-resistant thick cotton throw for patio evenings.",
    description:
      "A heavier-weight waffle weave designed specifically for outdoor living. This blanket keeps out the evening chill on the terrace while remaining fully breathable. Finished with a modern self-fringed edge.",
    material: "100% durable long-staple cotton",
    details: [
      "Heavier 480 GSM weight for wind resistance",
      "Fray-resistant self-fringed edges",
      "Generously sized for sharing",
      "Fade-resistant yarn dyeing",
    ],
    care: ["Machine wash cold", "Tumble dry low", "Do not bleach"],
    colors: ["Clay", "Sage", "Charcoal"],
    images: [u("1519710164239-da123dc03ef4"), u("1567016432779-094069958ea5")],
    sizes: [{ name: "One Size", dimensions: "150 × 200 cm", price: 11500, compare_at_price: null }],
    badge: null,
    featured: false,
    in_stock: true,
  },
  {
    id: "p22",
    slug: "terracotta-planter-trio",
    name: "Terracotta Planter Trio",
    category_slug: "garden",
    short_description: "Hand-pressed planters that weather beautifully.",
    description:
      "Pressed and fired the traditional way, these terracotta planters breathe with the plant — roots stay healthy, and the clay takes on a soft patina season by season. Three nested sizes, drainage holes included.",
    material: "Hand-pressed terracotta, unglazed",
    details: [
      "Set of three: 12, 16 and 20 cm diameters",
      "Drainage hole and matching saucer for each",
      "Breathable unglazed clay for healthy roots",
      "Weathers to a soft patina outdoors",
    ],
    care: ["Soak before first planting", "Bring indoors in extreme heat spells to slow drying"],
    colors: ["Terracotta", "Whitewash"],
    images: [u("1485955900006-10f4d324d411"), u("1459156212016-c812468e2115")],
    sizes: [{ name: "Set of 3", dimensions: "Ø 12 / 16 / 20 cm", price: 6900, compare_at_price: null }],
    badge: "New",
    featured: true,
    in_stock: true,
  },
  // ── Garage ─────────────────────────────────────────────────────────────
  {
    id: "p24",
    slug: "heavy-linen-storage",
    name: "Heavy Linen Storage Baskets",
    category_slug: "garage",
    short_description: "Structured storage baskets with natural leather handles.",
    description:
      "Keep utility rooms, pantries and mudrooms organized. Sewn from double-layered heavy linen canvas, these storage baskets stand upright on their own and fold flat when not in use. Finished with double-riveted tan leather handles.",
    material: "100% heavy linen canvas, genuine leather handles",
    details: [
      "Stands upright independently",
      "Double-riveted top-grain leather handles",
      "Collapsible design for easy storage",
      "Neutral linen texture hides dust",
    ],
    care: ["Wipe clean with a damp cloth", "Do not submerge leather handles in water"],
    colors: ["Natural Linen", "Charcoal Linen"],
    images: [u("1532882772249-df68a5dffc3e"), u("1522771739844-6a9f6d5f14af")],
    sizes: [
      { name: "Medium", dimensions: "30 × 30 × 30 cm", price: 7900, compare_at_price: null },
      { name: "Large", dimensions: "40 × 40 × 40 cm", price: 9800, compare_at_price: null },
    ],
    badge: null,
    featured: true,
    in_stock: true,
  },
  {
    id: "p25",
    slug: "canvas-utility-organizer",
    name: "Canvas Utility Hanging Organizer",
    category_slug: "garage",
    short_description: "Wall-mounted heavy canvas pocket organizer with brass grommets.",
    description:
      "A premium solution for organizing small tools, garden shears and utility accessories. Woven from 18oz heavy waxed cotton canvas, this hanging organizer features 8 pockets of varying sizes and reinforced brass hanging grommets.",
    material: "100% waxed cotton canvas, brass grommets",
    details: [
      "8 structured pockets (4 small, 4 large)",
      "Three reinforced brass hanging grommets",
      "Water-resistant waxed finish",
      "Perfect for garage, workshop, or greenhouse walls",
    ],
    care: ["Wipe clean only", "Do not wash or dry clean (wax finish)"],
    colors: ["Olive", "Oatmeal"],
    images: [u("1581235720704-06d3acfcb36f"), u("1590794056226-79ef3a8147e1")],
    sizes: [{ name: "Standard", dimensions: "50 × 80 cm", price: 11000, compare_at_price: null }],
    badge: null,
    featured: false,
    in_stock: true,
  },
  {
    id: "p26",
    slug: "waxed-canvas-tool-roll",
    name: "Waxed Canvas Tool Roll",
    category_slug: "garage",
    short_description: "Twelve-slot tool roll in waxed canvas and leather.",
    description:
      "The good tools deserve better than a drawer. Twelve graded slots in 18oz waxed canvas keep chisels, drivers and secateurs organised and rust-free, rolled tight with double leather straps.",
    material: "18oz waxed cotton canvas, leather straps",
    details: [
      "12 graded slots plus a zipped pocket",
      "Water-resistant waxed finish",
      "Double leather straps with brass buckles",
      "Rolls to the size of a wine bottle",
    ],
    care: ["Wipe clean only", "Re-wax yearly for full weather resistance"],
    colors: ["Olive", "Tan"],
    images: [u("1530124566582-a618bc2615dc"), u("1504148455328-c376907d081c")],
    sizes: [{ name: "One Size", dimensions: "50 × 36 cm open", price: 5900, compare_at_price: null }],
    badge: null,
    featured: false,
    in_stock: true,
  },
];
